language: python
dist: trusty
sudo: required
matrix:
  include:
  - python: 2.7
    services: docker
branches:
  except:
  - "/^.*-wip$/"
install:
- travis/travis_install.sh
script:
- travis/travis_script.sh
after_success:
- travis/travis_after_success.sh
- ls wheelhouse/
deploy:
  provider: s3
  access_key_id: AKIAISG4H2IJZLISXOPQ
  secret_access_key:
    secure: DAuc3n+JLxlBmCLgQuLSXwIRHropTVK/TWj3jD99aB1+Bzy5CpmPtXyR3DGltGF2Bum52xcRM8dLFktinFkMqKF7UKZRGNwEey07Nhen94AGjkLomeEM0SRRjVP6T8RqLBK+buNcoRqiFTNM+JlW5ndY6Wy+kFaan+qk3UNz570=
  bucket: pycryptodome-releases
  local_dir: wheelhouse
  skip_cleanup: true
  acl: public_read
  on:
    all_branches: true
    repo: Legrandin/pycryptodome
