language: python
dist: trusty
python:
 - "2.6"
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"
 - "3.6"
 - "pypy"
 - "pypy3"
env:
 - CFFI=no
 - CFFI=yes
matrix:
 exclude:
 - python: pypy
   env: CFFI=no
 - python: pypy3
   env: CFFI=no
 include:
 - python: 2.7
   env: CFFI=no OLDPY=python2.4
 - python: 2.7
   env: CFFI=no OLDPY=python2.5
 - python: 2.7
 - python: 3.4
   env: CFFI=no OLDPY=python3.2
 - python: 3.4
   env: CFFI=yes OLDPY=python3.2
branches:
 except:
  - /^.*-wip$/
install:
 - ./travis_install.sh
script:
 #- export PYTHONPATH=${PWD}/custom_packages
 - if [ x${OLDPY} == x ]; then export PYTHON=python; else export PYTHON=${OLDPY} PYTHONPATH=${PWD}/custom_packages; fi
 - echo ${PYTHON}
 - PYVERSION=$(${PYTHON} -V 2>&1)
 - echo ${PYVERSION}
 - ${PYTHON} -c "import cffi" 2>/dev/null && echo CFFI is installed || true
 - if [ x${CFFI} = "xyes" ]; then ${PYTHON} -c"import cffi"; fi
 - if [ x${CFFI} != "xyes" ]; then ! ${PYTHON} -c"import cffi" 2>/dev/null; fi
 - MAJOR=$(echo ${PYVERSION} | cut -f2 -d' ' | cut -f1 -d'.')
 - if [ "${MAJOR}" -ge 3 ]; then xflags="$xflags -bb" ; fi
 - if [[ ${PYVERSION} != *"PyPy"* ]] || [ "${MAJOR}" -lt 3 ]; then xflags="$xflags -tt"; fi
 - echo "Custom Python flags:" \"${xflags:-none}\"
 - ${PYTHON} $xflags setup.py build
 - ${PYTHON} $xflags setup.py test
